### ISSUE TITLE
Port to Python 3.x

### ISSUE THREAD

**Issue by laenan8466** [gha2012/mtsslSuite#2]
Hello,
first, thank's for the MtsslSuite! Do you plan to port it to python 3.x?
Cheers,
Dennis

**Comment by gha2012** [comment]
Hi,
No, but I am currently developing a web server version of the whole suite. Are you interested to try the beta?
Cheers,
Gregor

**Comment by laenan8466** [comment]
Hey Gregor,
Sounds great and something I had also in mind, if I would have time some day. ;-)
So yes, I would love to test it and give some feedback. But be aware, I didn't used the MtsslSuite a lot till now. I used MMM most of the time, but proteins aren't my main topic. (Ok, I simulated a rotamer library etc...)
You can also send me an email (dennis.buecker@uni-konstanz.de)
Cheers,
Dennis
